from pathlib import Path

REPO=Path(__file__).resolve().parents[1]
MODEL=REPO/"generator/model/production_integrity_audit.py"
TEST=REPO/"tests/test_production_integrity_audit.py"

MODEL_TEXT = 'from dataclasses import dataclass\n\n@dataclass(frozen=True, slots=True)\nclass Finding:\n    identifier: str\n    severity: str\n    area: str\n    summary: str\n    state: str\n    routing_blocker: bool\n    resolution_evidence: str = ""\n\nFINDINGS = (\n    Finding(\n        "AE036-F01","P0","build-system",\n        "clean build can delete native PCB",\n        "CLOSED",False,\n        "AE-036A/B preserve native PCB/design-rule artifacts during generator cleanup; validated by clean build and regression."\n    ),\n    Finding(\n        "AE036-F02","P0","SCH101",\n        "cartridge loading/common-mode bias/RF response not closed",\n        "CLOSED",False,\n        "AE-037/037A/037B/037C3 define 47.4k differential loading, explicit DC bias return, 47p common-mode RF shunts, optional 22p differential DNP, and reconcile placement."\n    ),\n    Finding(\n        "AE036-F03","P0/P1","physical-CAD",\n        "dual op-amp package/unit semantics not closed",\n        "CLOSED",False,\n        "AE-038/039A/039B/B1/039C/C1/C2B establish 10 physical op-amp packages, real KiCad A/B units, actual SOIC-8 pin semantics, and explicit follower feedback."\n    ),\n    Finding("AE036-F04","P1","controls","Grayhill remains selected in live authority after rejection","OPEN",False),\n    Finding("AE036-F05","P1","controls-PCB","PCB-mounted controls are not yet physical PCB objects","OPEN",False),\n    Finding("AE036-F06","P1","power","nominal ±18 V uses top of key IC recommended range","OPEN",False),\n    Finding("AE036-F07","P1","governance","decision/current baseline and indexes are stale","OPEN",False),\n    Finding("AE036-F08","P1","PCB-authority","native pipeline retains superseded mounting-hole state","OPEN",False),\n    Finding("AE036-F09","P1","PCB-audit","native-board text audits are structurally weak","OPEN",False),\n    Finding("AE036-F10","P1/P2","procurement","BOM/approved-parts catalogue incomplete","OPEN",False),\n    Finding("AE036-F11","P2","CI","CI omits production build and KiCad gates","OPEN",False),\n    Finding("AE036-F12","P2","mechanical","final connector/interface arrangement needs confirmation","OPEN",False),\n    Finding("AE036-F13","P2","maintenance","maintenance/release pack awaits physical evidence","OPEN",False),\n)\n\ndef open_findings():\n    return tuple(x for x in FINDINGS if x.state=="OPEN")\n\ndef closed_findings():\n    return tuple(x for x in FINDINGS if x.state=="CLOSED")\n\ndef routing_blockers():\n    return tuple(x for x in FINDINGS if x.state=="OPEN" and x.routing_blocker)\n\ndef validate_findings():\n    assert len({x.identifier for x in FINDINGS}) == len(FINDINGS)\n    assert {x.state for x in FINDINGS} <= {"OPEN","CLOSED"}\n    assert {x.identifier for x in closed_findings()} == {\n        "AE036-F01","AE036-F02","AE036-F03"\n    }\n    assert all(x.resolution_evidence for x in closed_findings())\n    assert routing_blockers() == ()\n'
TEST_TEXT = 'from generator.model.production_integrity_audit import (\n    FINDINGS, closed_findings, open_findings, routing_blockers, validate_findings\n)\n\ndef test_ae036_findings_are_well_formed():\n    validate_findings()\n\ndef test_original_three_routing_hold_items_are_formally_closed():\n    assert {x.identifier for x in closed_findings()} == {\n        "AE036-F01","AE036-F02","AE036-F03"\n    }\n\ndef test_repository_wide_routing_hold_is_lifted():\n    assert routing_blockers() == ()\n\ndef test_build_native_pcb_hazard_remains_historical_p0_but_closed():\n    f=next(x for x in FINDINGS if x.identifier=="AE036-F01")\n    assert f.severity=="P0"\n    assert f.state=="CLOSED"\n    assert not f.routing_blocker\n\ndef test_remaining_findings_begin_at_f04():\n    assert {x.identifier for x in open_findings()} == {\n        "AE036-F04","AE036-F05","AE036-F06","AE036-F07","AE036-F08",\n        "AE036-F09","AE036-F10","AE036-F11","AE036-F12","AE036-F13"\n    }\n'

def main():
    MODEL.write_text(MODEL_TEXT,encoding="utf-8")
    TEST.write_text(TEST_TEXT,encoding="utf-8")
    print("AE-040A APPLIED")
    print("AE036-F01/F02/F03 -> CLOSED")
    print("Repository-wide AE-036 routing hold -> LIFTED")
    print("Remaining open findings: F04-F13")

if __name__=="__main__":
    main()