"""AE-041 controlled mechanical evidence for Shellac control hardware."""
from __future__ import annotations
from dataclasses import dataclass
@dataclass(frozen=True, slots=True)
class MechanicalEvidence:
    identifier:str; manufacturer:str; mpn:str; function:str; mounting:str; behind_panel_depth_mm:float|None=None; shaft_diameter_mm:float|None=None; shaft_projection_mm:float|None=None; bushing_thread:str|None=None; bushing_length_mm:float|None=None; panel_cutout_mm:float|None=None; body_length_mm:float|None=None; body_depth_mm:float|None=None; body_height_mm:float|None=None; evidence_grade:str="E1/E3"; manufacturing_released:bool=False; notes:str=""
GRAYHILL_1_DECK=MechanicalEvidence("MECH-SW901-902-HISTORICAL","Grayhill","71BDF30-01-2-AJN","Bass/Treble rotary — rejected historical candidate","panel + through-hole PC mount, right-angle",behind_panel_depth_mm=19.33,shaft_diameter_mm=6.35,shaft_projection_mm=9.53,bushing_thread="3/8-32 UNEF",bushing_length_mm=7.92,notes="REJECTED by AE-026; retained for traceability only.")
GRAYHILL_2_DECK=MechanicalEvidence("MECH-SW903-HISTORICAL","Grayhill","71BDF30-02-2-AJN","Channel Mode rotary — rejected historical candidate","panel + through-hole PC mount, right-angle",behind_panel_depth_mm=24.87,shaft_diameter_mm=6.35,shaft_projection_mm=9.53,bushing_thread="3/8-32 UNEF",bushing_length_mm=7.92,notes="REJECTED by AE-026; retained for traceability only.")
NKK_NR01=MechanicalEvidence("MECH-SW901L-R-SW902L-R","NKK","NR01 family","Independent L/R Bass and Treble selectors","PCB rotary with threaded panel registration",evidence_grade="E1 family authority; exact order code open",notes="AE-041 selected family. Four independent controls total; exact production MPN remains open.")
CK_A30403RNCB=MechanicalEvidence("MECH-SW903","C&K","A30403RNCB","Channel-mode 3P4T rotary","panel + through-hole PC mount",behind_panel_depth_mm=14.48,shaft_diameter_mm=6.35,shaft_projection_mm=9.53,body_length_mm=26.2,panel_cutout_mm=9.8,evidence_grade="E1 exact-MPN/family evidence",notes="3P4T, 4-position, 30-degree, non-shorting/BBM, low-level gold contacts; preferred production part; matrix knob KN900B1/4. Exact detent-to-terminal CW mapping requires continuity confirmation before manufacturing release.")
TE_MRJE3404=MechanicalEvidence("MECH-SW903-FALLBACK","TE/Alcoswitch","MRJE3404","Channel-mode 3P4T rotary procurement fallback","panel + through-hole PC mount",shaft_diameter_mm=3.17,evidence_grade="E1/E3 exact-MPN evidence",notes="3P4T, 4-position, BBM, 0.4 VA at 20 V, gold finish; stocked fallback. Requires different knob/shaft treatment from preferred C&K part.")
CK_7201SYCBE=MechanicalEvidence("MECH-SW904-905","C&K / Littelfuse","7201SYCBE","Rumble/Mute common toggle","PC pins + threaded panel bushing",shaft_projection_mm=10.67,bushing_thread="1/4-40",bushing_length_mm=8.89,panel_cutout_mm=6.35,body_length_mm=12.70,body_depth_mm=11.43,body_height_mm=8.89,evidence_grade="E1 exact product electrical + E3 exact-MPN dimensions",notes="DPDT ON-ON, gold contacts, epoxy-sealed terminals.")
LED_BEZEL=MechanicalEvidence("MECH-LED901-902-BEZEL","Arcolectric / Bulgin","A104700BLACK","3 mm rail-indicator bezel","panel-mounted brass holder",panel_cutout_mm=6.30,body_length_mm=13.90,body_depth_mm=7.60,evidence_grade="E3 authorised-distributor exact-MPN data")
ROTARY_PLATFORM_AUTHORITY={"eq_manufacturer":"NKK","eq_family":"NR01","eq_quantity":4,"eq_exact_mpn_status":"OPEN","matrix_manufacturer":"C&K","matrix_mpn":"A30403RNCB","matrix_fallback_mpn":"TE/Alcoswitch MRJE3404","matrix_status":"PREFERRED_PROCUREMENT_PARTIAL","authority":"AE-041 A1"}
HISTORICAL_ROTARY_EVIDENCE=(GRAYHILL_1_DECK,GRAYHILL_2_DECK); CURRENT_ROTARY_EVIDENCE=(NKK_NR01,CK_A30403RNCB); EXTERNAL_CONTROL_CONTRACTS=(CK_A30403RNCB,TE_MRJE3404,CK_7201SYCBE,LED_BEZEL)
def validate_control_mechanical_evidence()->None:
    assert all("REJECTED" in item.notes for item in HISTORICAL_ROTARY_EVIDENCE)
    assert ROTARY_PLATFORM_AUTHORITY["matrix_mpn"]=="A30403RNCB" and CK_A30403RNCB.shaft_diameter_mm==6.35
    assert ROTARY_PLATFORM_AUTHORITY["matrix_fallback_mpn"]=="TE/Alcoswitch MRJE3404"
    assert CK_7201SYCBE.panel_cutout_mm==6.35 and LED_BEZEL.panel_cutout_mm==6.30
    assert all(not item.manufacturing_released for item in CURRENT_ROTARY_EVIDENCE+(TE_MRJE3404,CK_7201SYCBE,LED_BEZEL))
